export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS'

export const ME_REQUEST = 'ME_REQUEST'
export const ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS'
export const ME_UPDATE_REQUEST = 'ME_UPDATE_REQUEST'
export const ME_UPDATE_REQUEST_SUCCESS = 'ME_UPDATE_REQUEST_SUCCESS'

export const ALERT_ERROR = 'ALERT_ERROR'
export const ALERT_SUCCESS = 'ALERT_SUCCESS'

export const CONNECTION_CHANGED = 'CONNECTION_CHANGED'

export const REACT_NAVIGATION_NAVIGATE = 'Navigation/NAVIGATE'
export const REACT_NAVIGATION_RESET_NAVIGATION = 'Navigation/RESET'
export const REACT_NAVIGATION_BACK = 'Navigation/BACK'

export const APP_RESET_AND_NAVIGATE = 'APP_RESET_AND_NAVIGATE'

export const REQUEST_START = 'REQUEST_START'
export const REQUEST_END = 'REQUEST_END'
